let currentUser=null;let selected={gym:false,cardio:false,yoga:false,steps10k:false,steps15k:false,restDay:false};const $=id=>document.getElementById(id);const todayISO=()=>new Date().toISOString().slice(0,10);
function init(){memberSelect.innerHTML=MEMBERS.map(m=>`<option>${m.name}</option>`).join('');adminMember.innerHTML=MEMBERS.map(m=>`<option>${m.name}</option>`).join('');adminDate.value=todayISO();todayText.textContent=new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'});document.querySelectorAll('.activity').forEach(btn=>btn.onclick=()=>toggleActivity(btn));loginBtn.onclick=login;logoutBtn.onclick=logout;submitBtn.onclick=submitToday;refreshBtn.onclick=loadLeaderboard;adminSaveBtn.onclick=adminSave;adminDeleteBtn.onclick=adminDelete;exportBtn.onclick=exportCSV;loadLeaderboard()}
function login(){const name=memberSelect.value,pin=pinInput.value.trim();const member=MEMBERS.find(m=>m.name===name&&m.pin===pin);if(!member){loginMsg.textContent='Incorrect name or PIN.';return}currentUser=member;loginCard.classList.add('hidden');entryCard.classList.remove('hidden');logoutBtn.classList.remove('hidden');welcomeTitle.textContent=`Welcome, ${member.name}`;roleBadge.textContent=member.admin?'Admin':'Member';if(member.admin)adminCard.classList.remove('hidden')}
function logout(){currentUser=null;loginCard.classList.remove('hidden');entryCard.classList.add('hidden');adminCard.classList.add('hidden');logoutBtn.classList.add('hidden');pinInput.value=''}
function toggleActivity(btn){const key=btn.dataset.key;if(key==='restDay'){selected={gym:false,cardio:false,yoga:false,steps10k:false,steps15k:false,restDay:!selected.restDay}}else{selected.restDay=false;selected[key]=!selected[key];if(key==='steps10k'&&selected.steps10k)selected.steps15k=false;if(key==='steps15k'&&selected.steps15k)selected.steps10k=false}renderActivityButtons()}
function renderActivityButtons(){document.querySelectorAll('.activity').forEach(btn=>btn.classList.toggle('active',selected[btn.dataset.key]));todayScore.textContent=calculatePoints(selected)}
function calculatePoints(e){if(e.restDay)return 0;const raw=(e.gym?1:0)+(e.cardio?1:0)+(e.yoga?.5:0)+(e.steps10k?.5:0)+(e.steps15k?1:0);return Math.min(2,raw)}
function api(action,payload={}){if(LOCAL_DEMO_MODE)return Promise.resolve(localApi(action,payload));return new Promise((resolve,reject)=>{const cb='jsonpCallback_'+Date.now()+'_'+Math.floor(Math.random()*100000);const script=document.createElement('script');window[cb]=res=>{delete window[cb];script.remove();resolve(res)};script.onerror=()=>{delete window[cb];script.remove();reject(new Error('Could not connect to Google Apps Script.'))};const params = new URLSearchParams({
  action: action,
  payload: JSON.stringify({ action: action, ...payload }),
  callback: cb
});script.src=`${API_URL}?${params.toString()}`;document.body.appendChild(script)})}
async function submitToday(){if(!currentUser)return;const entry={member:currentUser.name,date:todayISO(),...selected,points:calculatePoints(selected)};const result=await api('saveEntry',{entry,pin:currentUser.pin});submitMsg.textContent=result.message||'Saved.';loadLeaderboard()}
async function loadLeaderboard(){const result=await api('leaderboard',{});const rows=result.leaderboard||[];leaderboard.innerHTML=rows.map((r,i)=>`<div class="rank-card"><div class="rank-top"><div><span class="badge">#${i+1}</span> <span class="rank-name">${r.member}</span></div><div class="rank-score">${r.total}</div></div><div class="stats"><div class="stat"><b>${r.weekly}</b>Week</div><div class="stat"><b>${r.gymCardioDays}</b>Gym+Cardio</div><div class="stat"><b>${r.stepDays}</b>Step Days</div><div class="stat"><b>${r.restDays}</b>Rest</div></div></div>`).join('')||"<p class='muted'>No entries yet.</p>"}
async function adminSave(){if(!currentUser?.admin)return;const entry={member:adminMember.value,date:adminDate.value,gym:aGym.checked,cardio:aCardio.checked,yoga:aYoga.checked,steps10k:a10k.checked,steps15k:a15k.checked,restDay:aRest.checked};if(entry.restDay){entry.gym=entry.cardio=entry.yoga=entry.steps10k=entry.steps15k=false}if(entry.steps15k)entry.steps10k=false;entry.points=calculatePoints(entry);const result=await api('adminSave',{entry,adminPin:currentUser.pin});adminMsg.textContent=result.message||'Admin entry saved.';loadLeaderboard()}
async function adminDelete(){if(!currentUser?.admin)return;const result=await api('adminDelete',{member:adminMember.value,date:adminDate.value,adminPin:currentUser.pin});adminMsg.textContent=result.message||'Entry deleted.';loadLeaderboard()}
async function exportCSV(){const result=await api('exportCSV',{});const blob=new Blob([result.csv||''],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='gym-challenge-export.csv';a.click();URL.revokeObjectURL(url)}
function localApi(action,payload){const key='gymChallengeEntries';let entries=JSON.parse(localStorage.getItem(key)||'[]');const upsert=entry=>{entries=entries.filter(e=>!(e.member===entry.member&&e.date===entry.date));entries.push(entry);localStorage.setItem(key,JSON.stringify(entries))};if(action==='saveEntry'||action==='adminSave'){upsert(payload.entry);return{success:true,message:'Saved in demo mode. Connect Google Apps Script for group syncing.'}}if(action==='adminDelete'){entries=entries.filter(e=>!(e.member===payload.member&&e.date===payload.date));localStorage.setItem(key,JSON.stringify(entries));return{success:true,message:'Deleted in demo mode.'}}if(action==='exportCSV')return{csv:entriesToCSV(entries)};return{leaderboard:buildLeaderboard(entries)}}
function entriesToCSV(entries){const h=['date','member','gym','cardio','yoga','steps10k','steps15k','restDay','points'];return h.join(',')+'\n'+entries.map(e=>h.map(x=>e[x]).join(',')).join('\n')}
function buildLeaderboard(entries){const totals={};MEMBERS.forEach(m=>totals[m.name]={member:m.name,total:0,weekly:0,gymCardioDays:0,stepDays:0,restDays:0});entries.forEach(e=>{const r=totals[e.member];r.total+=Number(e.points||0);r.weekly+=Number(e.points||0);if(e.gym&&e.cardio)r.gymCardioDays++;if(e.steps10k||e.steps15k)r.stepDays++;if(e.restDay)r.restDays++});return Object.values(totals).sort((a,b)=>b.total-a.total).map(r=>({...r,total:score(r.total),weekly:score(r.weekly)}))}function score(n){return Math.round(n*10)/10}init();
